//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnableGPlayWithPC.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnableGPlayWithPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   adb.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdbPath {
            get {
                return ResourceManager.GetString("AdbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not found.
        ///Please check to exist that file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_404_Desc {
            get {
                return ResourceManager.GetString("Dialog_404_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_404_Inst {
            get {
                return ResourceManager.GetString("Dialog_404_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adb.exe is not found.
        ///Please check adb.exe&apos;s path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Adb404_Desc {
            get {
                return ResourceManager.GetString("Dialog_Adb404_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adb.exe is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Adb404_Inst {
            get {
                return ResourceManager.GetString("Dialog_Adb404_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not a benesse product tablet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Not_Benesse_Tab_Desc {
            get {
                return ResourceManager.GetString("Dialog_Not_Benesse_Tab_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Benesse tablet not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Not_Benesse_Tab_Inst {
            get {
                return ResourceManager.GetString("Dialog_Not_Benesse_Tab_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google functions are enabled!
        ///You can continue using your device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Successed_Desc {
            get {
                return ResourceManager.GetString("Dialog_Successed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Successed_Inst {
            get {
                return ResourceManager.GetString("Dialog_Successed_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many connected devices.
        ///Please connect only one devices. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_TooManyDevices_Desc {
            get {
                return ResourceManager.GetString("Dialog_TooManyDevices_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many connected devices に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_TooManyDevices_Inst {
            get {
                return ResourceManager.GetString("Dialog_TooManyDevices_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect your device.
        ///Please check connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_UnableToConnect_Desc {
            get {
                return ResourceManager.GetString("Dialog_UnableToConnect_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect your device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_UnableToConnect_Inst {
            get {
                return ResourceManager.GetString("Dialog_UnableToConnect_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .apk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelector_Extension {
            get {
                return ResourceManager.GetString("FileSelector_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open .apk file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelector_Title {
            get {
                return ResourceManager.GetString("FileSelector_Title", resourceCulture);
            }
        }
    }
}
